#!/usr/bin/env bash

search_dirs=(~ ~/Projects ~/.config)

find_directories() {
    find "${search_dirs[@]}" -mindepth 1 -maxdepth 1 -type d
}

find_symlinked_directories() {
    find "${search_dirs[@]}" -mindepth 1 -maxdepth 1 -type l -exec test -d {} \; -print
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$((find_directories; find_symlinked_directories) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
selected_name=${selected_name:0:7}

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

