general.import = ["~/.config/alacritty/colors/rose-pine-custom.toml"]

[scrolling]
history = 10000

[font]
size = 20

[font.normal]
family = "Hack Nerd Font"

[window]
title = ""
decorations = "full"
dynamic_title = false
decorations_theme_variant = "Dark"
option_as_alt = "Both"

opacity = 0.96
blur = false

[window.padding]
x = 4
y = 4
